In [ ]:
import numpy as np

#задание 1
massive=np.array([1,7,10,12,14])
print (massive)



#задание 2
two_massive=np.array([[1,2,3],[4,5,6]])
print (two_massive)

# использованием функций `zeros`, `ones`, `arange`
massive_zeros=np.zeros((2,5))
print (massive_zeros)

arr_massive=np.arange(10,25,0.5)
print (arr_massive)
 
#задание 3
print (two_massive.shape)
print (two_massive.dtype)

#задание 4
indx_massive=massive[2]
print (indx_massive) 
slice_massive=massive[1:4]
print (slice_massive)

#задание 5
# Векторное умножение элементов
massive_one=np.array([10,20,30,40,50])
massibe_two=np.array([1,2,3,4,5])
sum_massive=massive_one*massibe_two
print (sum_massive)
#вычисление средней величины
mean_massive=massive_one.mean()
print (mean_massive)




[ 1  7 10 12 14]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5]
(2, 3)
int64
10
[ 7 10 12]
[ 10  40  90 160 250]
30.0


: 